Bugfix: Time class couldn't serialize with to_msgpack
To resolve this issue, convert Time to String class with to_s.

Regression:
$ irb
require 'time'
require 'msgpack'
Time.parse("2013-11-22 17:30:00 +0900").to_msgpack
NoMethodError: undefined method `to_msgpack' for 2013-11-22 17:30:00
+0900:Time

Related issue:
https://github.com/msgpack/msgpack-python/issues/12